// Expo config plugin: finishes the home-screen widget providers generated by
// react-native-android-widget, whose own config can't express these:
//
// - android:minResizeWidth / minResizeHeight: its config only knows
//   minWidth/minHeight (the *default* size on pre-Android 12 launchers) and
//   maxResize*, so without this a widget can't shrink below its default size.
// - android:initialLayout: its layout is empty until the first render, which
//   needs the app's JS to start - a placed widget showed nothing for about a
//   second. Ours is an empty card in the widget's shape and colour
//   (plugins/widget-res, copied into the Android res folder).
// - previews: moved to drawable-nodpi (the library copies them to drawable,
//   i.e. mdpi, so Android scaled the full-resolution images up another 2-3x
//   when loading them), plus dark variants from assets/widgets/night for
//   launchers in dark mode.
//
// Dangerous mods run newest-first, so this plugin must be listed *before*
// "react-native-android-widget" in app.json to patch the files after they
// have been generated.
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

function copyDir(from, to) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(dest, { recursive: true });
      copyDir(src, dest);
    } else {
      fs.copyFileSync(src, dest);
    }
  }
}

module.exports = function withWidgetProviderExtras(config, { widgets = {} } = {}) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;
      const res = path.join(platformProjectRoot, 'app/src/main/res');
      copyDir(path.join(__dirname, 'widget-res'), res);

      for (const [name, { minResizeWidth, minResizeHeight }] of Object.entries(widgets)) {
        const id = name.toLowerCase();
        const file = path.join(res, 'xml', `widgetprovider_${id}.xml`);
        if (fs.existsSync(file)) {
          let xml = fs.readFileSync(file, 'utf8');
          xml = xml.replace(/\s*android:minResize(Width|Height)="[^"]*"/g, '');
          xml = xml.replace(
            /(android:minHeight="[^"]*")/,
            `$1\n    android:minResizeWidth="${minResizeWidth}"\n    android:minResizeHeight="${minResizeHeight}"`
          );
          xml = xml.replace(
            /android:initialLayout="[^"]*"/,
            'android:initialLayout="@layout/tomo_widget_loading"'
          );
          fs.writeFileSync(file, xml);
        }

        const preview = `${id}_preview.png`;
        const generated = path.join(res, 'drawable', preview);
        if (fs.existsSync(generated)) {
          fs.mkdirSync(path.join(res, 'drawable-nodpi'), { recursive: true });
          fs.renameSync(generated, path.join(res, 'drawable-nodpi', preview));
        }
        const night = path.join(projectRoot, 'assets/widgets/night', `${id}.png`);
        if (fs.existsSync(night)) {
          fs.mkdirSync(path.join(res, 'drawable-night-nodpi'), { recursive: true });
          fs.copyFileSync(night, path.join(res, 'drawable-night-nodpi', preview));
        }
      }
      return cfg;
    },
  ]);
};
