// Expo config plugin: localised names and descriptions for the home-screen
// widgets in the launcher's widget picker. react-native-android-widget writes
// them as fixed English text (receiver android:label, a non-translatable
// description string); this points both at our own string resources, with a
// values-<locale> folder per app language (texts in widget-strings.json).
//
// Like withWidgetProviderExtras it must be listed *before*
// "react-native-android-widget" in app.json, so it runs after the library.
const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

const STRINGS = require('./widget-strings.json');

// App language → Android resource qualifiers. Traditional Chinese is matched
// by script on Android 7+ (b+zh+Hant), with region folders for older matching.
const QUALIFIERS = {
  en: ['values'],
  it: ['values-it'],
  es: ['values-es'],
  fr: ['values-fr'],
  de: ['values-de'],
  pt: ['values-pt'],
  'pt-BR': ['values-pt-rBR'],
  nl: ['values-nl'],
  pl: ['values-pl'],
  ja: ['values-ja'],
  ko: ['values-ko'],
  'zh-Hant': ['values-b+zh+Hant', 'values-zh-rTW', 'values-zh-rHK', 'values-zh-rMO'],
};

const FILE = 'tomo_widget_strings.xml';
const labelRes = (name) => `tomo_widget_${name.toLowerCase()}_label`;
const descRes = (name) => `tomo_widget_${name.toLowerCase()}_description`;

function escape(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/@/g, '\\@')
    .replace(/\?/g, '\\?');
}

/** Write values-<locale>/tomo_widget_strings.xml for every language. */
function writeWidgetStrings(resDir) {
  for (const [lang, dirs] of Object.entries(QUALIFIERS)) {
    const texts = STRINGS[lang];
    if (!texts) continue;
    const lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by plugins/withWidgetLabels.js from widget-strings.json -->', '<resources>'];
    for (const [name, { label, description }] of Object.entries(texts)) {
      lines.push(`  <string name="${labelRes(name)}">${escape(label)}</string>`);
      lines.push(`  <string name="${descRes(name)}">${escape(description)}</string>`);
    }
    lines.push('</resources>', '');
    for (const dir of dirs) {
      fs.mkdirSync(path.join(resDir, dir), { recursive: true });
      fs.writeFileSync(path.join(resDir, dir, FILE), lines.join('\n'));
    }
  }
}

/** Point each widget provider's description at the localised string. */
function patchProviders(resDir) {
  for (const name of Object.keys(STRINGS.en)) {
    const file = path.join(resDir, 'xml', `widgetprovider_${name.toLowerCase()}.xml`);
    if (!fs.existsSync(file)) continue;
    const xml = fs.readFileSync(file, 'utf8');
    fs.writeFileSync(file, xml.replace(/android:description="[^"]*"/, `android:description="@string/${descRes(name)}"`));
  }
}

/** Receiver labels (manifest XML as text, for the one-off script below). */
function patchManifestText(xml) {
  let out = xml;
  for (const name of Object.keys(STRINGS.en)) {
    const re = new RegExp(`(<receiver android:name="\\.widget\\.${name}"[^>]*android:label=")[^"]*(")`);
    out = out.replace(re, `$1@string/${labelRes(name)}$2`);
  }
  return out;
}

const withWidgetLabels = (config) => {
  config = withAndroidManifest(config, (cfg) => {
    const receivers = cfg.modResults.manifest.application?.[0]?.receiver ?? [];
    for (const r of receivers) {
      const name = String(r.$['android:name'] ?? '').replace(/^.*\.widget\./, '');
      if (STRINGS.en[name]) r.$['android:label'] = `@string/${labelRes(name)}`;
    }
    return cfg;
  });
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const res = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res');
      writeWidgetStrings(res);
      patchProviders(res);
      return cfg;
    },
  ]);
};

module.exports = withWidgetLabels;
module.exports.writeWidgetStrings = writeWidgetStrings;
module.exports.patchProviders = patchProviders;
module.exports.patchManifestText = patchManifestText;
